[project]
name = "globeco-script-runner"
version = "0.1.0"
description = "Generic Python runner for Kubernetes"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.4",
]
